### ISSUE TITLE
simple homepage design landing page ejs/react for demo

### ISSUE THREAD

**Issue by felmez** [RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary#34]

**Comment by felmez** [comment]
hello @Corcit when we designed the homepage on figma [link]( https://www.figma.com/file/2Ucm1OXU79c3Avsmr20IqH/homepage-design-last ) i already done some research about templates that are similar to design so we do frontend faster here is a free template (you dont have to go with its just a suggestions) that i found that you can use since its very similar to our figma design here maybe if dont want to get lost in the ocean of templates :)

i am attaching a zip file so you can download which has four templates that are very simple open and browse each template and choose the one that you find awesome :)) we trust you, good luck

[Shade Lite Files.zip](https://github.com/RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary/files/7981266/Shade.Lite.Files.zip)

**Comment by Corcit** [comment]
@felmez Thanks for heads up and pre-search :)
