### ISSUE TITLE
fix user routes module export

### ISSUE THREAD

**Issue by felmez** [RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary#51]
hello @yaman3bd here in the user routes file we are forgetting to export the routes, the app in this state is not working, idk how we did missed something like important :))

![image](https://user-images.githubusercontent.com/14183741/152257850-b781f018-fdbb-4bff-b3c6-3371e2dfdb3c.png)

![image](https://user-images.githubusercontent.com/14183741/152257894-b46e79d3-9deb-4d90-8045-f509019039b9.png)

**Comment by yaman3bd** [comment]
fixed in [add_user_crud_api ](https://github.com/RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary/pull/48)
